/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRentalRouteImport } from './routes/terms-rental'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OfferRouteImport } from './routes/offer'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EquipmentRouteImport } from './routes/equipment'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CasesRouteImport } from './routes/cases'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ZonesSlugRouteImport } from './routes/zones.$slug'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ProductionSlugRouteImport } from './routes/production.$slug'
import { Route as EquipmentSlugRouteImport } from './routes/equipment.$slug'
import { Route as CasesSlugRouteImport } from './routes/cases.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminPromoRouteImport } from './routes/admin.promo'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNewsletterRouteImport } from './routes/admin.newsletter'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as AdminCasesRouteImport } from './routes/admin.cases'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminAvailabilityRouteImport } from './routes/admin.availability'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminCatalogTypeRouteImport } from './routes/admin.catalog.$type'
import { Route as AdminOrdersIdQuoteRouteImport } from './routes/admin.orders.$id.quote'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRentalRoute = TermsRentalRouteImport.update({
  id: '/terms-rental',
  path: '/terms-rental',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferRoute = OfferRouteImport.update({
  id: '/offer',
  path: '/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipmentRoute = EquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesRoute = CasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ZonesSlugRoute = ZonesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ZonesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductionSlugRoute = ProductionSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductionRoute,
} as any)
const EquipmentSlugRoute = EquipmentSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EquipmentRoute,
} as any)
const CasesSlugRoute = CasesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CasesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromoRoute = AdminPromoRouteImport.update({
  id: '/promo',
  path: '/promo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsletterRoute = AdminNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCasesRoute = AdminCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAvailabilityRoute = AdminAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminCatalogTypeRoute = AdminCatalogTypeRouteImport.update({
  id: '/catalog/$type',
  path: '/catalog/$type',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdQuoteRoute = AdminOrdersIdQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => AdminOrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/cases': typeof CasesRouteWithChildren
  '/compare': typeof CompareRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/production': typeof ProductionRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-rental': typeof TermsRentalRoute
  '/testimonials': typeof TestimonialsRoute
  '/wishlist': typeof WishlistRoute
  '/zones': typeof ZonesRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/promo': typeof AdminPromoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/production/$slug': typeof ProductionSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalog/$type': typeof AdminCatalogTypeRoute
  '/admin/orders/$id': typeof AdminOrdersIdRouteWithChildren
  '/admin/orders/$id/quote': typeof AdminOrdersIdQuoteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/cases': typeof CasesRouteWithChildren
  '/compare': typeof CompareRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/production': typeof ProductionRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-rental': typeof TermsRentalRoute
  '/testimonials': typeof TestimonialsRoute
  '/wishlist': typeof WishlistRoute
  '/zones': typeof ZonesRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/promo': typeof AdminPromoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/production/$slug': typeof ProductionSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/catalog/$type': typeof AdminCatalogTypeRoute
  '/admin/orders/$id': typeof AdminOrdersIdRouteWithChildren
  '/admin/orders/$id/quote': typeof AdminOrdersIdQuoteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/calculator': typeof CalculatorRoute
  '/cart': typeof CartRoute
  '/cases': typeof CasesRouteWithChildren
  '/compare': typeof CompareRoute
  '/contacts': typeof ContactsRoute
  '/delivery': typeof DeliveryRoute
  '/equipment': typeof EquipmentRouteWithChildren
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
  '/offer': typeof OfferRoute
  '/partners': typeof PartnersRoute
  '/privacy': typeof PrivacyRoute
  '/production': typeof ProductionRouteWithChildren
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-rental': typeof TermsRentalRoute
  '/testimonials': typeof TestimonialsRoute
  '/wishlist': typeof WishlistRoute
  '/zones': typeof ZonesRouteWithChildren
  '/admin/audit': typeof AdminAuditRoute
  '/admin/availability': typeof AdminAvailabilityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/cases': typeof AdminCasesRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/admin/newsletter': typeof AdminNewsletterRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/promo': typeof AdminPromoRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/cases/$slug': typeof CasesSlugRoute
  '/equipment/$slug': typeof EquipmentSlugRoute
  '/production/$slug': typeof ProductionSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/zones/$slug': typeof ZonesSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/catalog/$type': typeof AdminCatalogTypeRoute
  '/admin/orders/$id': typeof AdminOrdersIdRouteWithChildren
  '/admin/orders/$id/quote': typeof AdminOrdersIdQuoteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/calculator'
    | '/cart'
    | '/cases'
    | '/compare'
    | '/contacts'
    | '/delivery'
    | '/equipment'
    | '/faq'
    | '/industries'
    | '/login'
    | '/offer'
    | '/partners'
    | '/privacy'
    | '/production'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms-rental'
    | '/testimonials'
    | '/wishlist'
    | '/zones'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/blog'
    | '/admin/calendar'
    | '/admin/cases'
    | '/admin/marketing'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/promo'
    | '/admin/testimonials'
    | '/admin/users'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/equipment/$slug'
    | '/production/$slug'
    | '/services/$slug'
    | '/zones/$slug'
    | '/admin/'
    | '/admin/catalog/$type'
    | '/admin/orders/$id'
    | '/admin/orders/$id/quote'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/calculator'
    | '/cart'
    | '/cases'
    | '/compare'
    | '/contacts'
    | '/delivery'
    | '/equipment'
    | '/faq'
    | '/industries'
    | '/login'
    | '/offer'
    | '/partners'
    | '/privacy'
    | '/production'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms-rental'
    | '/testimonials'
    | '/wishlist'
    | '/zones'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/blog'
    | '/admin/calendar'
    | '/admin/cases'
    | '/admin/marketing'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/promo'
    | '/admin/testimonials'
    | '/admin/users'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/equipment/$slug'
    | '/production/$slug'
    | '/services/$slug'
    | '/zones/$slug'
    | '/admin'
    | '/admin/catalog/$type'
    | '/admin/orders/$id'
    | '/admin/orders/$id/quote'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/calculator'
    | '/cart'
    | '/cases'
    | '/compare'
    | '/contacts'
    | '/delivery'
    | '/equipment'
    | '/faq'
    | '/industries'
    | '/login'
    | '/offer'
    | '/partners'
    | '/privacy'
    | '/production'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/terms-rental'
    | '/testimonials'
    | '/wishlist'
    | '/zones'
    | '/admin/audit'
    | '/admin/availability'
    | '/admin/blog'
    | '/admin/calendar'
    | '/admin/cases'
    | '/admin/marketing'
    | '/admin/newsletter'
    | '/admin/orders'
    | '/admin/promo'
    | '/admin/testimonials'
    | '/admin/users'
    | '/blog/$slug'
    | '/cases/$slug'
    | '/equipment/$slug'
    | '/production/$slug'
    | '/services/$slug'
    | '/zones/$slug'
    | '/admin/'
    | '/admin/catalog/$type'
    | '/admin/orders/$id'
    | '/admin/orders/$id/quote'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CalculatorRoute: typeof CalculatorRoute
  CartRoute: typeof CartRoute
  CasesRoute: typeof CasesRouteWithChildren
  CompareRoute: typeof CompareRoute
  ContactsRoute: typeof ContactsRoute
  DeliveryRoute: typeof DeliveryRoute
  EquipmentRoute: typeof EquipmentRouteWithChildren
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
  OfferRoute: typeof OfferRoute
  PartnersRoute: typeof PartnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductionRoute: typeof ProductionRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRentalRoute: typeof TermsRentalRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WishlistRoute: typeof WishlistRoute
  ZonesRoute: typeof ZonesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-rental': {
      id: '/terms-rental'
      path: '/terms-rental'
      fullPath: '/terms-rental'
      preLoaderRoute: typeof TermsRentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer': {
      id: '/offer'
      path: '/offer'
      fullPath: '/offer'
      preLoaderRoute: typeof OfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipment': {
      id: '/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof EquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases': {
      id: '/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof CasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/zones/$slug': {
      id: '/zones/$slug'
      path: '/$slug'
      fullPath: '/zones/$slug'
      preLoaderRoute: typeof ZonesSlugRouteImport
      parentRoute: typeof ZonesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/production/$slug': {
      id: '/production/$slug'
      path: '/$slug'
      fullPath: '/production/$slug'
      preLoaderRoute: typeof ProductionSlugRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/equipment/$slug': {
      id: '/equipment/$slug'
      path: '/$slug'
      fullPath: '/equipment/$slug'
      preLoaderRoute: typeof EquipmentSlugRouteImport
      parentRoute: typeof EquipmentRoute
    }
    '/cases/$slug': {
      id: '/cases/$slug'
      path: '/$slug'
      fullPath: '/cases/$slug'
      preLoaderRoute: typeof CasesSlugRouteImport
      parentRoute: typeof CasesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promo': {
      id: '/admin/promo'
      path: '/promo'
      fullPath: '/admin/promo'
      preLoaderRoute: typeof AdminPromoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/newsletter': {
      id: '/admin/newsletter'
      path: '/newsletter'
      fullPath: '/admin/newsletter'
      preLoaderRoute: typeof AdminNewsletterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cases': {
      id: '/admin/cases'
      path: '/cases'
      fullPath: '/admin/cases'
      preLoaderRoute: typeof AdminCasesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/availability': {
      id: '/admin/availability'
      path: '/availability'
      fullPath: '/admin/availability'
      preLoaderRoute: typeof AdminAvailabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/catalog/$type': {
      id: '/admin/catalog/$type'
      path: '/catalog/$type'
      fullPath: '/admin/catalog/$type'
      preLoaderRoute: typeof AdminCatalogTypeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders/$id/quote': {
      id: '/admin/orders/$id/quote'
      path: '/quote'
      fullPath: '/admin/orders/$id/quote'
      preLoaderRoute: typeof AdminOrdersIdQuoteRouteImport
      parentRoute: typeof AdminOrdersIdRoute
    }
  }
}

interface AdminOrdersIdRouteChildren {
  AdminOrdersIdQuoteRoute: typeof AdminOrdersIdQuoteRoute
}

const AdminOrdersIdRouteChildren: AdminOrdersIdRouteChildren = {
  AdminOrdersIdQuoteRoute: AdminOrdersIdQuoteRoute,
}

const AdminOrdersIdRouteWithChildren = AdminOrdersIdRoute._addFileChildren(
  AdminOrdersIdRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRouteWithChildren
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRouteWithChildren,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminAvailabilityRoute: typeof AdminAvailabilityRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminCasesRoute: typeof AdminCasesRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminNewsletterRoute: typeof AdminNewsletterRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPromoRoute: typeof AdminPromoRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCatalogTypeRoute: typeof AdminCatalogTypeRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminAvailabilityRoute: AdminAvailabilityRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminCasesRoute: AdminCasesRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminNewsletterRoute: AdminNewsletterRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPromoRoute: AdminPromoRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCatalogTypeRoute: AdminCatalogTypeRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CasesRouteChildren {
  CasesSlugRoute: typeof CasesSlugRoute
}

const CasesRouteChildren: CasesRouteChildren = {
  CasesSlugRoute: CasesSlugRoute,
}

const CasesRouteWithChildren = CasesRoute._addFileChildren(CasesRouteChildren)

interface EquipmentRouteChildren {
  EquipmentSlugRoute: typeof EquipmentSlugRoute
}

const EquipmentRouteChildren: EquipmentRouteChildren = {
  EquipmentSlugRoute: EquipmentSlugRoute,
}

const EquipmentRouteWithChildren = EquipmentRoute._addFileChildren(
  EquipmentRouteChildren,
)

interface ProductionRouteChildren {
  ProductionSlugRoute: typeof ProductionSlugRoute
}

const ProductionRouteChildren: ProductionRouteChildren = {
  ProductionSlugRoute: ProductionSlugRoute,
}

const ProductionRouteWithChildren = ProductionRoute._addFileChildren(
  ProductionRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface ZonesRouteChildren {
  ZonesSlugRoute: typeof ZonesSlugRoute
}

const ZonesRouteChildren: ZonesRouteChildren = {
  ZonesSlugRoute: ZonesSlugRoute,
}

const ZonesRouteWithChildren = ZonesRoute._addFileChildren(ZonesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CalculatorRoute: CalculatorRoute,
  CartRoute: CartRoute,
  CasesRoute: CasesRouteWithChildren,
  CompareRoute: CompareRoute,
  ContactsRoute: ContactsRoute,
  DeliveryRoute: DeliveryRoute,
  EquipmentRoute: EquipmentRouteWithChildren,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
  OfferRoute: OfferRoute,
  PartnersRoute: PartnersRoute,
  PrivacyRoute: PrivacyRoute,
  ProductionRoute: ProductionRouteWithChildren,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRentalRoute: TermsRentalRoute,
  TestimonialsRoute: TestimonialsRoute,
  WishlistRoute: WishlistRoute,
  ZonesRoute: ZonesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
